

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
Type.registerNamespace("SP.Portal.JsApi");

SP.Portal.JsApi.ShimPlaceholder = {};


SP.Portal.JsApi.ProjectSummary.Shim = function()
{

}

SP.Portal.JsApi.ProjectSummary.Shim.Wrap = function(wrappedImpl)
{
   function CallMethod(shim, name, params, bIsAsync, fnCallback, bCausesStateUpdate)
   {
      var callId = JsApi.InstrumentationManager.RaiseInvokingEvent(shim, name);

      if (bIsAsync)
      {
          params.push(HandleCallback);
      }

      var res = shim._impl[name].apply(shim._impl, params);

      if (!bIsAsync)
      {
         HandleCallback(true);
      }

      return res;

      // internal functions follow
      function HandleCallback(success, res)
      {
         JsApi.InstrumentationManager.RaiseEndedEvent(callId);

         if (bIsAsync)
         {
            if (fnCallback != null)
            {
               fnCallback(success, res);
            }
         }

         if (bCausesStateUpdate)
         {
            JsApi.ExtensibilityManager.NotifyStateUpdated(shim._impl);
         }
      }
   }
      wrappedImpl.get_IsRotationPaused = function()
      {
         return CallMethod(this, "get_IsRotationPaused", [], false, null, false);
      };
      wrappedImpl.set_IsRotationPaused = function(value)
      {
         return CallMethod(this, "set_IsRotationPaused", [value], false, null, true);
      };
      wrappedImpl.get_CountDownTextInfo = function()
      {
         return CallMethod(this, "get_CountDownTextInfo", [], false, null, false);
      };
      wrappedImpl.get_CountDownDueDate = function()
      {
         return CallMethod(this, "get_CountDownDueDate", [], false, null, false);
      };
      wrappedImpl.get_LateItems = function()
      {
         return CallMethod(this, "get_LateItems", [], false, null, false);
      };
      wrappedImpl.get_TotalLateItemsCount = function()
      {
         return CallMethod(this, "get_TotalLateItemsCount", [], false, null, false);
      };
      wrappedImpl.get_UpcomingItems = function()
      {
         return CallMethod(this, "get_UpcomingItems", [], false, null, false);
      };
      wrappedImpl.get_TotalUpcomingItemsCount = function()
      {
         return CallMethod(this, "get_TotalUpcomingItemsCount", [], false, null, false);
      };
      wrappedImpl.get_PrimaryTaskListLink = function()
      {
         return CallMethod(this, "get_PrimaryTaskListLink", [], false, null, false);
      };
      wrappedImpl.ShowNextHeadline = function()
      {
         return CallMethod(this, "ShowNextHeadline", [], false, null, false);
      };
      wrappedImpl.ShowPreviousHeadline = function()
      {
         return CallMethod(this, "ShowPreviousHeadline", [], false, null, false);
      };
};


if( window.Sys != null && Sys.Application != null ){
   Sys.Application.notifyScriptLoaded();
}

NotifyScriptLoadedAndExecuteWaitingJobs("SpsApiShim.generated.js");

