

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Type.registerNamespace('JsApiUtils'); JsApiUtils.NotifyStateUpdated = function(impl) { window.JsApi && JsApi.ExtensibilityManager && JsApi.ExtensibilityManager.NotifyStateUpdated(impl); }; 

Type.registerNamespace('SP.Timeline.InstrumentedApi');
              SP.Timeline.InstrumentedApi.ExecuteWithJsApiLoaded = function(fn) { var fnEx = window.ExecuteOrDelayUntilScriptLoaded && ExecuteOrDelayUntilScriptLoaded; fnEx && fnEx(function() { JsApi.ExtensibilityManager.ExecuteWithJsApisInNamespaceLoaded('SP.Timeline.InstrumentedApi', fn); }, 'JsApiExtensibilityManager.js'); };

Type.registerNamespace("SP.Timeline.InstrumentedApi");

SP.Timeline.InstrumentedApi.ClientApi = {
   None: 0,
                Timeline : 1
        
        }  


SP.Timeline.InstrumentedApi.JsApiWrapperFactory = function()
{
   function GetWrappedFunction(itemName, impl) 
   { 
       return function() 
       { 
           return impl[itemName].apply(impl, arguments); 
       }; 
   };

   return {
      Create: function(impl, shimtypeName, apiId)
      {
         // first level wrapper
         var ret = {};
         for (var itemName in impl)
         {
             if (impl[itemName] != null && impl[itemName].constructor == Function)
             {
                 ret[itemName] = GetWrappedFunction(itemName, impl);
             }
         }
         ret._impl = impl;
         ret._shimTypeName = shimtypeName;
         impl.get_Api = function() { return ret; }
         // note: there's bug in script# where it doesn't respect the [PreserveCase] attribute
         // on any properties that appear on interfaces, as such, we just put the name method here with casings.
         ret.get_impl = ret.get_Impl = function() { return this._impl; };
         ret.get_apiNamespaceKey = ret.get_ApiNamespaceKey = function() { return "SP.Timeline.InstrumentedApi"; };
         ret.get_ApiType = ret.get_apiType = function() { return apiId; };         
         JsApi.ExtensibilityManager._NotifyApiPresent(ret);
         return ret;
      }
   };
}();


SP.Timeline.InstrumentedApi.Timeline = function()
{
   // this function is going to be the constructor for our class
   var shimClass = function(impl)
   { 
      return SP.Timeline.InstrumentedApi.JsApiWrapperFactory.Create(
        impl, 
        "SP.Timeline.InstrumentedApi.Timeline.Shim",
        // SP.Timeline.InstrumentedApi.ClientApi.Timeline
        1);
   };
   
   shimClass.WrapImplementationInApiAndMarkInitComplete = function(impl) 
   {
        SP.Timeline.InstrumentedApi.ExecuteWithJsApiLoaded(
            function() 
            {
                var api = new SP.Timeline.InstrumentedApi.Timeline(impl);
                JsApi.ExtensibilityManager._NotifyApiInitComplete(api);
            });
   };
   
   return shimClass;
}();

if( window.Sys != null && Sys.Application != null ){
    Sys.Application.notifyScriptLoaded();
}

NotifyScriptLoadedAndExecuteWaitingJobs("TimelineSharedApi.generated.js");
  
